### ISSUE TITLE
Request for Assistance: Addressing Training Variations and Forecasting Discrepancies in the Informer Model

### ISSUE THREAD

**Issue by SRDdev** [helloboge/Informer2020#1]
Dear [helloboge](https://github.com/helloboge),

I hope this message finds you well. I've been an avid follower of your repository and **deeply appreciate** the significant effort you've dedicated to it. Your work has immensely contributed to my understanding of the intricacies of Informer Architecture.

**Issue 1: Training Variations**
I am encountering an issue with the Informer results. Despite keeping the hyper-parameters and dataset constant, I observe significant variations in the outputs with each training and prediction cycle. After some investigation, I suspect this might be due to the random initialization of weights. To address this, I am seeking your guidance on setting the weights to a fixed value. Could you please assist me in achieving this stability in the model outputs?

**Issue 2: Discrepancy in Forecasting Models**
I've noticed another issue. I have two models trained for forecasting, one for a 24-hour horizon and another for a 48-hour horizon. Surprisingly, when I compare the forecasts for the same timestamp, the two models yield different values. I'm perplexed by this inconsistency, and I wonder if you could shed some light on why such variations might occur between models trained on the same dataset with similar configurations.

Thank you for your time and expertise.

Best regards,
SRD

**Comment by SRDdev** [comment]
亲爱的 [helloboge](https://github.com/helloboge),

希望这封信能够找到你时一切安好。我一直是你仓库的忠实关注者，非常感谢你为此付出的巨大努力。你的工作极大地促进了我对Informer架构复杂性的理解。

**问题1：训练差异**
我在使用Informer进行结果分析时遇到了一个问题。尽管保持超参数和数据集不变，但我观察到每次训练和预测周期都存在显著的输出差异。经过一些调查，我怀疑这可能是由于权重的随机初始化导致的。为了解决这个问题，我寻求你在将权重设置为固定值方面的指导。你能帮助我实现模型输出的稳定吗？

**问题2：预测模型存在差异**
我还注意到另一个问题。我有两个模型用于预测，一个用于24小时的预测，另一个用于48小时的预测。令人惊讶的是，当我比较相同时间戳的预测时，这两个模型产生了不同的值。我对这种不一致感到困惑，想知道在相似配置的相同数据集上训练的模型之间为什么会出现这种差异。

感谢你的时间和专业知识。

此致敬礼，
SRD

**Comment by helloboge** [comment]
Dear SRDdev,

First of all, thank you very much for your attention. However, I am sorry that I am unable to answer your question. I know very little about this model and am currently studying it in detail. The model is based on Dr. Zhou's research, and you can consult with him. His GitHub address is: https://github.com/zhouhaoyi/Informer2020.git

**Comment by SRDdev** [comment]
Thank you 👍🏻
